package model;
// Generated 21-dic-2014 8:20:31 by Hibernate Tools 3.6.0



/**
 * CriteriohijoHasSitioevaluacionId generated by hbm2java
 */
public class CriteriohijoHasSitioevaluacionId  implements java.io.Serializable {


     private int criteriohijoCodigo;
     private int sitioevaluacionCodigo;

    public CriteriohijoHasSitioevaluacionId() {
    }

    public CriteriohijoHasSitioevaluacionId(int criteriohijoCodigo, int sitioevaluacionCodigo) {
       this.criteriohijoCodigo = criteriohijoCodigo;
       this.sitioevaluacionCodigo = sitioevaluacionCodigo;
    }
   
    public int getCriteriohijoCodigo() {
        return this.criteriohijoCodigo;
    }
    
    public void setCriteriohijoCodigo(int criteriohijoCodigo) {
        this.criteriohijoCodigo = criteriohijoCodigo;
    }
    public int getSitioevaluacionCodigo() {
        return this.sitioevaluacionCodigo;
    }
    
    public void setSitioevaluacionCodigo(int sitioevaluacionCodigo) {
        this.sitioevaluacionCodigo = sitioevaluacionCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CriteriohijoHasSitioevaluacionId) ) return false;
		 CriteriohijoHasSitioevaluacionId castOther = ( CriteriohijoHasSitioevaluacionId ) other; 
         
		 return (this.getCriteriohijoCodigo()==castOther.getCriteriohijoCodigo())
 && (this.getSitioevaluacionCodigo()==castOther.getSitioevaluacionCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCriteriohijoCodigo();
         result = 37 * result + this.getSitioevaluacionCodigo();
         return result;
   }   


}


