package model;
// Generated 07-ene-2015 13:43:48 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CriteriohijoHasSitioevaluacion generated by hbm2java
 */
public class CriteriohijoHasSitioevaluacion  implements java.io.Serializable {


     private CriteriohijoHasSitioevaluacionId id;
     private Sitioevaluacion sitioevaluacion;
     private Criteriohijo criteriohijo;
     private Puntuacion puntuacion;
     private Criteriopadre criteriopadre;
     private Date fecha;
     private String comentario;
     private String usuario;

    public CriteriohijoHasSitioevaluacion() {
    }

	
    public CriteriohijoHasSitioevaluacion(CriteriohijoHasSitioevaluacionId id, Sitioevaluacion sitioevaluacion, Criteriohijo criteriohijo, Puntuacion puntuacion, Criteriopadre criteriopadre) {
        this.id = id;
        this.sitioevaluacion = sitioevaluacion;
        this.criteriohijo = criteriohijo;
        this.puntuacion = puntuacion;
        this.criteriopadre = criteriopadre;
    }
    public CriteriohijoHasSitioevaluacion(CriteriohijoHasSitioevaluacionId id, Sitioevaluacion sitioevaluacion, Criteriohijo criteriohijo, Puntuacion puntuacion, Criteriopadre criteriopadre, Date fecha, String comentario, String usuario) {
       this.id = id;
       this.sitioevaluacion = sitioevaluacion;
       this.criteriohijo = criteriohijo;
       this.puntuacion = puntuacion;
       this.criteriopadre = criteriopadre;
       this.fecha = fecha;
       this.comentario = comentario;
       this.usuario = usuario;
    }
   
    public CriteriohijoHasSitioevaluacionId getId() {
        return this.id;
    }
    
    public void setId(CriteriohijoHasSitioevaluacionId id) {
        this.id = id;
    }
    public Sitioevaluacion getSitioevaluacion() {
        return this.sitioevaluacion;
    }
    
    public void setSitioevaluacion(Sitioevaluacion sitioevaluacion) {
        this.sitioevaluacion = sitioevaluacion;
    }
    public Criteriohijo getCriteriohijo() {
        return this.criteriohijo;
    }
    
    public void setCriteriohijo(Criteriohijo criteriohijo) {
        this.criteriohijo = criteriohijo;
    }
    public Puntuacion getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Puntuacion puntuacion) {
        this.puntuacion = puntuacion;
    }
    public Criteriopadre getCriteriopadre() {
        return this.criteriopadre;
    }
    
    public void setCriteriopadre(Criteriopadre criteriopadre) {
        this.criteriopadre = criteriopadre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }




}


