package model;
// Generated 21-dic-2014 8:20:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Criteriohijo generated by hbm2java
 */
public class Criteriohijo  implements java.io.Serializable {


     private Integer codigo;
     private Criteriopadre criteriopadre;
     private String descripcion;
     private Set criteriohijoHasSitioevaluacions = new HashSet(0);

    public Criteriohijo() {
    }

	
    public Criteriohijo(Criteriopadre criteriopadre) {
        this.criteriopadre = criteriopadre;
    }
    public Criteriohijo(Criteriopadre criteriopadre, String descripcion, Set criteriohijoHasSitioevaluacions) {
       this.criteriopadre = criteriopadre;
       this.descripcion = descripcion;
       this.criteriohijoHasSitioevaluacions = criteriohijoHasSitioevaluacions;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Criteriopadre getCriteriopadre() {
        return this.criteriopadre;
    }
    
    public void setCriteriopadre(Criteriopadre criteriopadre) {
        this.criteriopadre = criteriopadre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCriteriohijoHasSitioevaluacions() {
        return this.criteriohijoHasSitioevaluacions;
    }
    
    public void setCriteriohijoHasSitioevaluacions(Set criteriohijoHasSitioevaluacions) {
        this.criteriohijoHasSitioevaluacions = criteriohijoHasSitioevaluacions;
    }




}


