package model;
// Generated 19-mar-2015 6:57:49 by Hibernate Tools 3.6.0

import model.Sitioevaluacion;
import model.Usuario;




/**
 * Estadisticaprompuntajebyusuario generated by hbm2java
 */
public class Estadisticaprompuntajebyusuario  implements java.io.Serializable {


     private EstadisticaprompuntajebyusuarioId id;
     private Usuario usuario;
     private Sitioevaluacion sitioevaluacion;
     private Double criterio1;
     private Double criterio2;
     private Double criterio3;
     private Double criterio4;
     private Double criterio5;
     private Double criterio6;
     private Double criterio7;
     private Double criterio8;
     private Double criterio9;
     private Double criterio10;

    public Estadisticaprompuntajebyusuario() {
    }

	
    public Estadisticaprompuntajebyusuario(EstadisticaprompuntajebyusuarioId id, Usuario usuario, Sitioevaluacion sitioevaluacion) {
        this.id = id;
        this.usuario = usuario;
        this.sitioevaluacion = sitioevaluacion;
    }
    public Estadisticaprompuntajebyusuario(EstadisticaprompuntajebyusuarioId id, Usuario usuario, Sitioevaluacion sitioevaluacion, Double criterio1, Double criterio2, Double criterio3, Double criterio4, Double criterio5, Double criterio6, Double criterio7, Double criterio8, Double criterio9, Double criterio10) {
       this.id = id;
       this.usuario = usuario;
       this.sitioevaluacion = sitioevaluacion;
       this.criterio1 = criterio1;
       this.criterio2 = criterio2;
       this.criterio3 = criterio3;
       this.criterio4 = criterio4;
       this.criterio5 = criterio5;
       this.criterio6 = criterio6;
       this.criterio7 = criterio7;
       this.criterio8 = criterio8;
       this.criterio9 = criterio9;
       this.criterio10 = criterio10;
    }
   
    public EstadisticaprompuntajebyusuarioId getId() {
        return this.id;
    }
    
    public void setId(EstadisticaprompuntajebyusuarioId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Sitioevaluacion getSitioevaluacion() {
        return this.sitioevaluacion;
    }
    
    public void setSitioevaluacion(Sitioevaluacion sitioevaluacion) {
        this.sitioevaluacion = sitioevaluacion;
    }
    public Double getCriterio1() {
        return this.criterio1;
    }
    
    public void setCriterio1(Double criterio1) {
        this.criterio1 = criterio1;
    }
    public Double getCriterio2() {
        return this.criterio2;
    }
    
    public void setCriterio2(Double criterio2) {
        this.criterio2 = criterio2;
    }
    public Double getCriterio3() {
        return this.criterio3;
    }
    
    public void setCriterio3(Double criterio3) {
        this.criterio3 = criterio3;
    }
    public Double getCriterio4() {
        return this.criterio4;
    }
    
    public void setCriterio4(Double criterio4) {
        this.criterio4 = criterio4;
    }
    public Double getCriterio5() {
        return this.criterio5;
    }
    
    public void setCriterio5(Double criterio5) {
        this.criterio5 = criterio5;
    }
    public Double getCriterio6() {
        return this.criterio6;
    }
    
    public void setCriterio6(Double criterio6) {
        this.criterio6 = criterio6;
    }
    public Double getCriterio7() {
        return this.criterio7;
    }
    
    public void setCriterio7(Double criterio7) {
        this.criterio7 = criterio7;
    }
    public Double getCriterio8() {
        return this.criterio8;
    }
    
    public void setCriterio8(Double criterio8) {
        this.criterio8 = criterio8;
    }
    public Double getCriterio9() {
        return this.criterio9;
    }
    
    public void setCriterio9(Double criterio9) {
        this.criterio9 = criterio9;
    }
    public Double getCriterio10() {
        return this.criterio10;
    }
    
    public void setCriterio10(Double criterio10) {
        this.criterio10 = criterio10;
    }




}


