package model;
// Generated 21-dic-2014 8:20:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estadoprueba generated by hbm2java
 */
public class Estadoprueba  implements java.io.Serializable {


     private Integer codigo;
     private String descripcion;
     private Set sitioevaluacions = new HashSet(0);

    public Estadoprueba() {
    }

    public Estadoprueba(String descripcion, Set sitioevaluacions) {
       this.descripcion = descripcion;
       this.sitioevaluacions = sitioevaluacions;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSitioevaluacions() {
        return this.sitioevaluacions;
    }
    
    public void setSitioevaluacions(Set sitioevaluacions) {
        this.sitioevaluacions = sitioevaluacions;
    }




}


