package model;
// Generated 19-mar-2015 6:57:49 by Hibernate Tools 3.6.0



/**
 * EstadisticaprompuntajebyusuarioId generated by hbm2java
 */
public class EstadisticaprompuntajebyusuarioId  implements java.io.Serializable {


     private int usuarioId;
     private int sitioevaluacionCodigo;

    public EstadisticaprompuntajebyusuarioId() {
    }

    public EstadisticaprompuntajebyusuarioId(int usuarioId, int sitioevaluacionCodigo) {
       this.usuarioId = usuarioId;
       this.sitioevaluacionCodigo = sitioevaluacionCodigo;
    }
   
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public int getSitioevaluacionCodigo() {
        return this.sitioevaluacionCodigo;
    }
    
    public void setSitioevaluacionCodigo(int sitioevaluacionCodigo) {
        this.sitioevaluacionCodigo = sitioevaluacionCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstadisticaprompuntajebyusuarioId) ) return false;
		 EstadisticaprompuntajebyusuarioId castOther = ( EstadisticaprompuntajebyusuarioId ) other; 
         
		 return (this.getUsuarioId()==castOther.getUsuarioId())
 && (this.getSitioevaluacionCodigo()==castOther.getSitioevaluacionCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioId();
         result = 37 * result + this.getSitioevaluacionCodigo();
         return result;
   }   


}


