package model;
// Generated 16-nov-2014 9:04:47 by Hibernate Tools 3.6.0



/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String titulo;
     private String contenido;
     private String dia;
     private String mes;
     private String anio;
     private String hora;
     private Sitioevaluacion sitioevaluacion;

    public Post() {
    }

	
    public Post(Usuario usuario) {
        this.id = 0;
        this.usuario = new Usuario();
        this.sitioevaluacion = new Sitioevaluacion();
    }
    public Post(Usuario usuario, String titulo, String contenido, String dia, String mes, String anio, String hora,Sitioevaluacion sitioevaluacion) {
       this.usuario = usuario;
       this.titulo = titulo;
       this.contenido = contenido;
       this.dia = dia;
       this.mes = mes;
       this.anio = anio;
       this.hora = hora;
       this.sitioevaluacion = sitioevaluacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    public Sitioevaluacion getSitioevaluacion() {
        return sitioevaluacion;
    }

    public void setSitioevaluacion(Sitioevaluacion sitioevaluacion) {
        this.sitioevaluacion = sitioevaluacion;
    }

    



}


