package model;
// Generated 21-dic-2014 8:20:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Puntuacion generated by hbm2java
 */
public class Puntuacion  implements java.io.Serializable {


     private int escala;
     private String descripcion;
     private Set criteriohijoHasSitioevaluacions = new HashSet(0);

    public Puntuacion() {
    }

	
    public Puntuacion(int escala) {
        this.escala = escala;
    }
    public Puntuacion(int escala, String descripcion, Set criteriohijoHasSitioevaluacions) {
       this.escala = escala;
       this.descripcion = descripcion;
       this.criteriohijoHasSitioevaluacions = criteriohijoHasSitioevaluacions;
    }
   
    public int getEscala() {
        return this.escala;
    }
    
    public void setEscala(int escala) {
        this.escala = escala;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCriteriohijoHasSitioevaluacions() {
        return this.criteriohijoHasSitioevaluacions;
    }
    
    public void setCriteriohijoHasSitioevaluacions(Set criteriohijoHasSitioevaluacions) {
        this.criteriohijoHasSitioevaluacions = criteriohijoHasSitioevaluacions;
    }




}


