package model;
// Generated 17-mar-2015 20:14:39 by Hibernate Tools 3.6.0

import model.Sitioevaluacion;
import model.Usuario;




/**
 * SitioevaluacionHasUsuarioPromEval generated by hbm2java
 */
public class SitioevaluacionHasUsuarioPromEval  implements java.io.Serializable {


     private SitioevaluacionHasUsuarioPromEvalId id;
     private Usuario usuario;
     private Sitioevaluacion sitioevaluacion;
     private Double promedio;

    public SitioevaluacionHasUsuarioPromEval() {
    }

	
    public SitioevaluacionHasUsuarioPromEval(SitioevaluacionHasUsuarioPromEvalId id, Usuario usuario, Sitioevaluacion sitioevaluacion) {
        this.id = id;
        this.usuario = usuario;
        this.sitioevaluacion = sitioevaluacion;
    }
    public SitioevaluacionHasUsuarioPromEval(SitioevaluacionHasUsuarioPromEvalId id, Usuario usuario, Sitioevaluacion sitioevaluacion, Double promedio) {
       this.id = id;
       this.usuario = usuario;
       this.sitioevaluacion = sitioevaluacion;
       this.promedio = promedio;
    }
   
    public SitioevaluacionHasUsuarioPromEvalId getId() {
        return this.id;
    }
    
    public void setId(SitioevaluacionHasUsuarioPromEvalId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Sitioevaluacion getSitioevaluacion() {
        return this.sitioevaluacion;
    }
    
    public void setSitioevaluacion(Sitioevaluacion sitioevaluacion) {
        this.sitioevaluacion = sitioevaluacion;
    }
    public Double getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(Double promedio) {
        this.promedio = promedio;
    }




}


