package model;
// Generated 21-dic-2014 8:20:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Lob;

/**
 * Sitioevaluacion generated by hbm2java
 */
public class Sitioevaluacion  implements java.io.Serializable {


     private Integer codigo;
     private Estadoprueba estadoprueba;
     private String nombre;
     private String url;
     private String tipo;
     private Date fechaEvaluacion;
     private Set usuarioHasSitioevaluacions = new HashSet(0);
     private Set criteriohijoHasSitioevaluacions = new HashSet(0);
     @Lob()
     private byte[] rutaImagen;

    public Sitioevaluacion() {
        this.codigo = 0;
        this.estadoprueba = new Estadoprueba();
    }

	
    public Sitioevaluacion(Estadoprueba estadoprueba) {
        this.estadoprueba = estadoprueba;
    }
    public Sitioevaluacion(Estadoprueba estadoprueba, String nombre, String url, String tipo, Date fechaEvaluacion, Set usuarioHasSitioevaluacions, Set criteriohijoHasSitioevaluacions) {
       this.estadoprueba = estadoprueba;
       this.nombre = nombre;
       this.url = url;
       this.tipo = tipo;
       this.fechaEvaluacion = fechaEvaluacion;
       this.usuarioHasSitioevaluacions = usuarioHasSitioevaluacions;
       this.criteriohijoHasSitioevaluacions = criteriohijoHasSitioevaluacions;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Estadoprueba getEstadoprueba() {
        return this.estadoprueba;
    }
    
    public void setEstadoprueba(Estadoprueba estadoprueba) {
        this.estadoprueba = estadoprueba;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFechaEvaluacion() {
        return this.fechaEvaluacion;
    }
    
    public void setFechaEvaluacion(Date fechaEvaluacion) {
        this.fechaEvaluacion = fechaEvaluacion;
    }
    public Set getUsuarioHasSitioevaluacions() {
        return this.usuarioHasSitioevaluacions;
    }
    
    public void setUsuarioHasSitioevaluacions(Set usuarioHasSitioevaluacions) {
        this.usuarioHasSitioevaluacions = usuarioHasSitioevaluacions;
    }
    public Set getCriteriohijoHasSitioevaluacions() {
        return this.criteriohijoHasSitioevaluacions;
    }
    
    public void setCriteriohijoHasSitioevaluacions(Set criteriohijoHasSitioevaluacions) {
        this.criteriohijoHasSitioevaluacions = criteriohijoHasSitioevaluacions;
    }

    public byte[] getRutaImagen() {
        return rutaImagen;
    }

    public void setRutaImagen(byte[] rutaImagen) {
        this.rutaImagen = rutaImagen;
    }




}


