package model;
// Generated 21-dic-2014 8:20:31 by Hibernate Tools 3.6.0



/**
 * UsuarioHasSitioevaluacion generated by hbm2java
 */
public class UsuarioHasSitioevaluacion  implements java.io.Serializable {


     private UsuarioHasSitioevaluacionId id;
     private Usuario usuario;
     private Sitioevaluacion sitioevaluacion;
     private Integer numEvaluadores;

    public UsuarioHasSitioevaluacion() {
    }

	
    public UsuarioHasSitioevaluacion(UsuarioHasSitioevaluacionId id, Usuario usuario, Sitioevaluacion sitioevaluacion) {
        this.id = id;
        this.usuario = usuario;
        this.sitioevaluacion = sitioevaluacion;
    }
    public UsuarioHasSitioevaluacion(UsuarioHasSitioevaluacionId id, Usuario usuario, Sitioevaluacion sitioevaluacion, Integer numEvaluadores) {
       this.id = id;
       this.usuario = usuario;
       this.sitioevaluacion = sitioevaluacion;
       this.numEvaluadores = numEvaluadores;
    }
   
    public UsuarioHasSitioevaluacionId getId() {
        return this.id;
    }
    
    public void setId(UsuarioHasSitioevaluacionId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Sitioevaluacion getSitioevaluacion() {
        return this.sitioevaluacion;
    }
    
    public void setSitioevaluacion(Sitioevaluacion sitioevaluacion) {
        this.sitioevaluacion = sitioevaluacion;
    }
    public Integer getNumEvaluadores() {
        return this.numEvaluadores;
    }
    
    public void setNumEvaluadores(Integer numEvaluadores) {
        this.numEvaluadores = numEvaluadores;
    }




}


